FROM golang:1.18 as builder

ENV CGO_ENABLED=0

WORKDIR /app
COPY . .

RUN go get -d -v ./...
RUN go build -o ./build/ cmd/chan/main.go

#############

FROM alpine:latest

COPY --from=builder /app/build .

CMD ["./main"]
